apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: katt--argo-workflows
  namespace: argocd
spec:
  project: kind
  source:
    repoURL: 'https://github.com/amanibhavam/spiral-katt'
    path: argo-workflows
    targetRevision: master
  destination:
    name: katt
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
