apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: katt--external-secrets
  namespace: argocd
spec:
  project: katt
  source:
    repoURL: 'https://github.com/amanibhavam/spiral-katt'
    path: external-secrets
    targetRevision: master
  destination:
    name: katt
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
