apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: katt--metacontroller
  namespace: argocd
spec:
  project: katt
  source:
    repoURL: 'https://github.com/amanibhavam/spiral-katt'
    path: metacontroller
    targetRevision: master
  destination:
    name: katt
    namespace: metacontroller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
