apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: katt--traefik-forward-auth
  namespace: argocd
spec:
  project: katt
  source:
    repoURL: 'https://github.com/letfn/katt-traefik-forward-auth'
    path: google
    targetRevision: master
  destination:
    name: katt
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
